site_name: 开源世界旅行手册
site_url: https://qundao.github.io/opensource-guide
site_description: 
copyright: A backup of <a href="https://i.linuxtoy.org/docs/guide/">《开源世界旅行手册》</a> 版权 © 2009 Kardinal
repo_url: https://github.com/qundao/opensource-guide

theme:
  name: material
  language: "zh"
  icon:
    logo: material/island
    repo: fontawesome/brands/github-alt
  font:
    text: Open Sans, Helvetica Neue, Roboto, sans-serif, serif
    code: Fira Mono, Fira Code, Roboto Mono, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

nav:
  - 首页: index.md
  - 前言:
    - 授权: pr01.md
    - 致谢: pr02.md
    - 序言: pr03.md
    - 更新纪录: pr04.md
    - 导读: pr05.md
    - 如何写作科技文档: pr06.md
  - I. 气候: 
    - pt01.md
    - 1. GUI? CLI?: ch01.md
    - 2. UNIX 缩写风格: 
      - ch02.md
      - ch02s02.md
      - ch02s03.md
    - 3. 版本号的迷雾: ch03.md
    - 4. Vim 还是 Emacs: ch04.md
    - 5. DocBook 还是 TeX: ch05.md
    - 6. 完全用 Gnu/Linux 工作:
      - ch06.md
      - ch06s02.md
      - ch06s03.md
      - ch06s04.md
      - ch06s05.md
      - ch06s06.md
      - ch06s07.md
      - ch06s08.md
      - ch06s09.md
      - ch06s10.md
      - ch06s11.md
      - ch06s12.md
      - ch06s13.md
    - 7. 病毒:
      - ch07.md
      - ch07s02.md
      - ch07s03.md
      - ch07s04.md
    - 8. 磁盘 分区:
      - ch08.md
      - ch08s02.md
    - 9. 文件系统: ch09.md
    - 10. 发行版介绍: ch10.md
    - 11. 编程语言: ch11.md
    - 12. 无根的根：无名师的 Unix 心传:
      - ch12.md
      - ch12s02.md
      - ch12s03.md
      - ch12s04.md
      - ch12s05.md
      - ch12s06.md
      - ch12s07.md
      - ch12s08.md
      - ch12s09.md
  - II. 地理: 
    - pt02.md
    - 13. 基础知识:
      - ch13.md
      - ch13s02.md
      - ch13s03.md
      - ch13s04.md
      - ch13s05.md
      - ch13s06.md
      - ch13s07.md
      - ch13s08.md
      - ch13s09.md
      - ch13s10.md
      - ch13s11.md
    - 14. 命令系统:
      - ch14.md
      - ch14s02.md
      - ch14s03.md
      - ch14s04.md
      - ch14s05.md
      - ch14s06.md
      - ch14s07.md
      - ch14s08.md
    - 15. 基本系统:
      - ch15.md
      - ch15s02.md
      - ch15s03.md
      - ch15s04.md
      - ch15s05.md
      - ch15s06.md
    - 16. 软件管理:
      - ch16.md
      - ch16s02.md
      - ch16s03.md
    - 17. 核心工具集:
      - ch17.md
      - ch17s02.md
      - ch17s03.md
      - ch17s04.md
      - ch17s05.md
      - ch17s06.md
      - ch17s07.md
      - ch17s08.md
      - ch17s09.md
      - ch17s10.md
      - ch17s11.md
      - ch17s12.md
      - ch17s13.md
      - ch17s14.md
    - 18. 编译工具链:
      - ch18.md
      - ch18s02.md
      - ch18s03.md
      - ch18s04.md
      - ch18s05.md
      - ch18s06.md
      - ch18s07.md
    - 19. 图形界面:
      - ch19.md
      - ch19s02.md
      - ch19s03.md
      - ch19s04.md
      - ch19s05.md
      - ch19s06.md
      - ch19s07.md
    - 20. 国际化:
      - ch20.md
      - ch20s02.md
      - ch20s03.md
      - ch20s04.md
    - 21. 内核:
      - ch21.md
      - ch21s02.md
      - ch21s03.md
      - ch21s04.md
      - ch21s05.md
    - 22. Grub:
      - ch22.md
      - ch22s02.md
      - ch22s03.md
      - ch22s04.md
      - ch22s05.md
      - ch22s06.md
      - ch22s07.md
    - 23. 服务器:
      - ch23.md
      - ch23s02.md
      - ch23s03.md
      - ch23s04.md
      - ch23s05.md
    - 24. Vim 编辑器:
      - ch24.md
      - ch24s02.md
      - ch24s03.md
      - ch24s04.md
      - ch24s05.md
      - ch24s06.md
      - ch24s07.md
      - ch24s08.md
      - ch24s09.md
      - ch24s10.md
      - ch24s11.md
      - ch24s12.md
      - ch24s13.md
      - ch24s14.md
      - ch24s15.md
      - ch24s16.md
      - ch24s17.md
      - ch24s18.md
      - ch24s19.md
      - ch24s20.md
      - ch24s21.md
      - ch24s22.md
      - ch24s23.md
      - ch24s24.md
      - ch24s25.md
    - 25. Emacs 入门:
      - ch25.md
      - ch25s02.md
      - ch25s03.md
      - ch25s04.md
      - ch25s05.md
      - ch25s06.md
      - ch25s07.md
      - ch25s08.md
      - ch25s09.md
      - ch25s10.md
      - ch25s11.md
      - ch25s12.md
      - ch25s13.md
      - ch25s14.md
      - ch25s15.md
      - ch25s16.md
      - ch25s17.md
      - ch25s18.md
      - ch25s19.md
      - ch25s20.md
    - 26. 正则表达式:
      - ch26.md
      - ch26s02.md
      - ch26s03.md
      - ch26s04.md
      - ch26s05.md
      - ch26s06.md
      - ch26s07.md
      - ch26s08.md
      - ch26s09.md
    - 27. docbook 指南:
      - ch27.md
      - ch27s02.md
      - ch27s03.md
      - ch27s04.md
      - ch27s05.md
      - ch27s06.md
      - ch27s07.md
      - ch27s08.md
      - ch27s09.md
      - ch27s10.md
      - ch27s11.md
      - ch27s12.md
      - ch27s13.md
      - ch27s14.md
      - ch27s15.md
      - ch27s16.md
      - ch27s17.md
      - ch27s18.md
      - ch27s19.md
      - ch27s20.md
      - ch27s21.md
      - ch27s22.md
    - 28. Git 版本控制系统:
      - ch28.md
      - ch28s02.md
      - ch28s03.md
      - ch28s04.md
      - ch28s05.md
      - ch28s06.md
      - ch28s07.md
      - ch28s08.md
      - ch28s09.md
      - ch28s10.md
    - 29. ConTeXt 入门指南:
      - ch29.md
      - ch29s02.md
      - ch29s03.md
      - ch29s04.md
      - ch29s05.md
      - ch29s06.md
      - ch29s07.md
      - ch29s08.md
      - ch29s09.md
      - ch29s10.md
      - ch29s11.md
      - ch29s12.md
      - ch29s13.md
  - III. 景观: 
    - pt03.md
    - 30. 终极 Shell -- ZSH:
      - ch30.md
      - ch30s02.md
      - ch30s03.md
      - ch30s04.md
    - 31. 完美工作站 Archlinux:
      - ch31.md
      - ch31s02.md
      - ch31s03.md
      - ch31s04.md
      - ch31s05.md
      - ch31s06.md
      - ch31s07.md
      - ch31s08.md
      - ch31s09.md
      - ch31s10.md
      - ch31s11.md
    - 32. 组织你的意念：Emacs org mode:
      - ch32.md
      - ch32s02.md
      - ch32s03.md
      - ch32s04.md
      - ch32s05.md
      - ch32s06.md
      - ch32s07.md
      - ch32s08.md
    - 33. Zsh+screen:
      - ch33.md
      - ch33s02.md
      - ch33s03.md
    - 34. gentoo stage3: ch34.md
    - 35. 硬件问题: ch35.md
    - 36. 网络设置: ch36.md
    - 37. 自制 LiveCD: ch37.md
    - 38. awesome:
      - ch38.md
      - ch38s02.md
      - ch38s03.md
      - ch38s04.md
      - ch38s05.md
    - 39. openbox 工作环境:
      - ch39.md
      - ch39s02.md
      - ch39s03.md
      - ch39s04.md
      - ch39s05.md
      - ch39s06.md
    - 40. Emacs muse: ch40.md
    - 41. 写作工具链: ch41.md
    - 42. 使用 lftp:
      - ch42.md
      - ch42s02.md
      - ch42s03.md
      - ch42s04.md
      - ch42s05.md
    - 43. Firefox 使用技巧:
      - ch43.md
      - ch43s02.md
    - 44. FVWM: ch44.md
  - IV. 地质: 
    - pt04.md
    - 45. Unix:
      - ch45.md
      - ch45s02.md
      - ch45s03.md
      - ch45s04.md
      - ch45s05.md
    - 46. Gnu: ch46.md
    - 47. 软件业自由之神——Richard Stallman:
      - ch47.md
      - ch47s02.md
      - ch47s03.md
      - ch47s04.md
      - ch47s05.md
      - ch47s06.md
      - ch47s07.md
      - ch47s08.md
      - ch47s09.md
    - 48. Linux:
      - ch48.md
      - ch48s02.md
      - ch48s03.md
      - ch48s04.md
      - ch48s05.md
      - ch48s06.md
      - ch48s07.md
      - ch48s08.md
      - ch48s09.md
    - 49. GNOME与KDE的战争:
      - ch49.md
      - ch49s02.md
      - ch49s03.md
      - ch49s04.md
      - ch49s05.md
      - ch49s06.md
    - 50. Vim Emacs: ch50.md
    - 51. 年代纪: ch51.md
    - 52. 我的选择: ch52.md
    - 53. 补遗: ch53.md
  - 博客文章:
    - archives/opensource-guide.md
    - archives/opensource-guide-01.md
  - 原版备份: guide/index.md
