site_name: 开源世界旅行手册
site_url: https://hantang.github.io/wayback-opensource-guide
site_description: 
copyright: A backup of <a href="https://i.linuxtoy.org/docs/guide/">《开源世界旅行手册》</a> 版权 © 2009 Kardinal
repo_url: https://github.com/hantang/wayback-opensource-guide

theme:
  name: material
  icon:
      logo: fontawesome/brands/git-alt
  font:
    text: Source Sans Pro, sans-serif
    code: Source Code Pro, Menlo, DejaVu Sans Mono, Lucida Console, monospace
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - content.code.copy

markdown_extensions:
  - abbr
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      line_spans: __span
      linenums_style: pymdownx-inline
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

nav:
  - 首页: index.md
  - 前言:
    - 授权: pr01.md
    - 致谢: pr02.md
    - 序言: pr03.md
    - 更新纪录: pr04.md
    - 导读: pr05.md
    - 如何写作科技文档: pr06.md
  - I. 气候: 
    - pt01.md
    - 1. GUI? CLI?: ch01.md
    - 2. UNIX 缩写风格: ch02.md
    - 3. 版本号的迷雾: ch03.md
    - 4. Vim 还是 Emacs: ch04.md
    - 5. DocBook 还是 TeX: ch05.md
    - 6. 完全用 Gnu/Linux 工作: ch06.md
    - 7. 病毒: ch07.md
    - 8. 磁盘 分区: ch08.md
    - 9. 文件系统: ch09.md
    - 10. 发行版介绍: ch10.md
    - 11. 编程语言: ch11.md
    - 12. 无根的根：无名师的 Unix 心传: ch12.md
  - II. 地理: 
    - pt02.md
    - 13. 基础知识: ch13.md
    - 14. 命令系统: ch14.md
    - 15. 基本系统: ch15.md
    - 16. 软件管理: ch16.md
    - 17. 核心工具集: ch17.md
    - 18. 编译工具链: ch18.md
    - 19. 图形界面: ch19.md
    - 20. 国际化: ch20.md
    - 21. 内核: ch21.md
    - 22. Grub: ch22.md
    - 23. 服务器: ch23.md
    - 24. Vim 编辑器: ch24.md
    - 25. Emacs 入门: ch25.md
    - 26. 正则表达式: ch26.md
    - 27. docbook 指南: ch27.md
    - 28. Git 版本控制系统: ch28.md
    - 29. ConTeXt 入门指南: ch29.md
  - III. 景观: 
    - pt03.md
    - 30. 终极 Shell -- ZSH: ch30.md
    - 31. 完美工作站 Archlinux: ch31.md
    - 32. 组织你的意念：Emacs org mode: ch32.md
    - 33. Zsh+screen: ch33.md
    - 34. gentoo stage3: ch34.md
    - 35. 硬件问题: ch35.md
    - 36. 网络设置: ch36.md
    - 37. 自制 LiveCD: ch37.md
    - 38. awesome: ch38.md
    - 39. openbox 工作环境: ch39.md
    - 40. Emacs muse: ch40.md
    - 41. 写作工具链: ch41.md
    - 42. 使用 lftp: ch42.md
    - 43. Firefox 使用技巧: ch43.md
    - 44. FVWM: ch44.md
  - IV. 地质: 
    - pt04.md
    - 45. Unix: ch45.md
    - 46. Gnu: ch46.md
    - 47. 软件业自由之神——Richard Stallman: ch47.md
    - 48. Linux: ch48.md
    - 49. GNOME与KDE的战争: ch49.md
    - 50. Vim Emacs: ch50.md
    - 51. 年代纪: ch51.md
    - 52. 我的选择: ch52.md
    - 53. 补遗: ch53.md
  - 原版备份: guide/index.md
